name: Release

on:
  release:
    types: [published]
    branches:
      - "main"

jobs:
  release:
    name: Release
    uses: molssi-seamm/devops/.github/workflows/Release.yaml@main
    with:
      src : seamm_manager
      # python_requires is >=3.12; do not test 3.11
      python-versions: '["3.12"]'
    secrets: inherit
